---
#- hosts: "{{ master }}"
#  remote_user: java
#  become: true
#
#  vars:
#      user: defined_vars
#      path: /path/defined
#
#  roles:
#    - role: test

- hosts: "{{ slave }}"
  remote_user: java
  become: true

  vars:
    user: defined_vars
    path: /path/defined

  roles:
    - role: test