socket: /data/mysql/mysql.sock
basedir: /usr/local/mysql
datadir: /data/mysql/
log_error: /data/mysql/mysql-error.log
pid_file: /data/mysql/mysqld.pid
log_bin: /data/mysql/mybinlog
path: /data
mysql_path: /data/mysql
mysql_root_pwd: root
package_path: /opt/software
slave_user: slave
slave_pwd: slave